# Set fixed portainer image
FROM portainer/portainer-ce:latest

# Set default admin password at startup
CMD ["--admin-password", "$2y$05$7i7DzUuxrgNW2VNDGp2aDupZpCzxpHo0bm1bHubqeZSHikApAMmUS"]

# Default portainer web port
EXPOSE 9000

